version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - krisp-assignment

  postgres:
    container_name: krisp-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - krisp-assignment

volumes:
  pgdata:

networks:
  krisp-assignment:
    name: krisp-assignment
    external: true
